package com.dmz.stock.view;

import com.dmz.stock.auxiliar.ConversorDateTime;
import com.dmz.stock.auxiliar.ConversorValores;
import com.dmz.stock.auxiliar.Expressoes;
import com.dmz.stock.controller.FornecedorProdutoController;
import com.dmz.stock.controller.ProdutoController;
import configuracoes.SystemMessage;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author seraf
 */
public class Arquivo extends javax.swing.JFrame {

    private static final Arquivo INSTANCE = new Arquivo();
    private ProdutoController produtoController = new ProdutoController();

    public static Arquivo getInstance() {
        return INSTANCE;
    }

    /**
     * Creates new form Arquivo
     */
    private Arquivo() {
        initComponents();
        configuracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEntrada = new javax.swing.ButtonGroup();
        buttonGroupSaida = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxMesEntrada = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserEntradaFinal = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jDateChooserEntradaInicial = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        btnPesquisarEntrada = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jRadioButtonEntradaMesPassado = new javax.swing.JRadioButton();
        jRadioButtonEntradaMesAtual = new javax.swing.JRadioButton();
        jRadioButtonEntradaOntem = new javax.swing.JRadioButton();
        jRadioButtonEntradaDiaHoje = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        txtIdProdutoEntrada = new javax.swing.JTextField();
        txtNomeProdutoEntrada = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblEntradaPeriodo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEntrada = new javax.swing.JTable();
        imprimirEntrada = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableSaida = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lblSaidaPeriodo = new javax.swing.JLabel();
        imprimirSaida = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxMesSaida = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jDateChooserSaidaFinal = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jDateChooserSaidaInicial = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jRadioButtonSaidaMesPassado = new javax.swing.JRadioButton();
        jRadioButtonSaidaMesActual = new javax.swing.JRadioButton();
        jRadioButtonSaidaMesOntem = new javax.swing.JRadioButton();
        jRadioButtonSaidaHoje = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        txtIdProdutoSaida = new javax.swing.JTextField();
        txtNomeProdutoSaida = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(26, 118, 141));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Entradas no Mês de:");

        jComboBoxMesEntrada.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jComboBoxMesEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMesEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxMesEntrada.setFocusable(false);
        jComboBoxMesEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMesEntradaMouseClicked(evt);
            }
        });
        jComboBoxMesEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesEntradaActionPerformed(evt);
            }
        });
        jComboBoxMesEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxMesEntradaKeyPressed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Data final:");

        jDateChooserEntradaFinal.setDateFormatString("dd - MM - yyyy");
        jDateChooserEntradaFinal.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Entradas entre datas:");

        jDateChooserEntradaInicial.setDateFormatString("dd - MM - yyyy");
        jDateChooserEntradaInicial.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("até");

        btnPesquisarEntrada.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-8-16.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Selecione o Outro mecanismo de Pesquisa:");

        jRadioButtonEntradaMesPassado.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupEntrada.add(jRadioButtonEntradaMesPassado);
        jRadioButtonEntradaMesPassado.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonEntradaMesPassado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEntradaMesPassado.setText("Entradas do Mês Passado");
        jRadioButtonEntradaMesPassado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonEntradaMesPassado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEntradaMesPassadoActionPerformed(evt);
            }
        });

        jRadioButtonEntradaMesAtual.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupEntrada.add(jRadioButtonEntradaMesAtual);
        jRadioButtonEntradaMesAtual.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonEntradaMesAtual.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEntradaMesAtual.setText("Entradas do Mês Actual");
        jRadioButtonEntradaMesAtual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonEntradaMesAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEntradaMesAtualActionPerformed(evt);
            }
        });

        jRadioButtonEntradaOntem.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupEntrada.add(jRadioButtonEntradaOntem);
        jRadioButtonEntradaOntem.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonEntradaOntem.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEntradaOntem.setText("Entradas do dia de Ontem");
        jRadioButtonEntradaOntem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonEntradaOntem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEntradaOntemActionPerformed(evt);
            }
        });

        jRadioButtonEntradaDiaHoje.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupEntrada.add(jRadioButtonEntradaDiaHoje);
        jRadioButtonEntradaDiaHoje.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonEntradaDiaHoje.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEntradaDiaHoje.setText("Entradas do dia de Hoje");
        jRadioButtonEntradaDiaHoje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonEntradaDiaHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEntradaDiaHojeActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Código de barras:");

        txtIdProdutoEntrada.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtIdProdutoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdProdutoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdProdutoEntradaKeyReleased(evt);
            }
        });

        txtNomeProdutoEntrada.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNomeProdutoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeProdutoEntradaKeyReleased(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Nome do Produto:");

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Código do Produto:");

        txtCodigoBarras.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtCodigoBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoBarrasKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMesEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserEntradaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserEntradaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonEntradaMesPassado)
                                    .addComponent(txtIdProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonEntradaMesAtual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonEntradaDiaHoje)
                                        .addGap(32, 32, 32)
                                        .addComponent(jRadioButtonEntradaOntem))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(txtNomeProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(29, 29, 29))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserEntradaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMesEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jDateChooserEntradaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEntradaMesPassado)
                    .addComponent(jRadioButtonEntradaMesAtual)
                    .addComponent(jRadioButtonEntradaOntem)
                    .addComponent(jRadioButtonEntradaDiaHoje))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProdutoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(jLabel33)))
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel15.setText("Entradas no Periodo:");

        lblEntradaPeriodo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblEntradaPeriodo.setText("0.0 MZN");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jTableEntrada.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTableEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Código", "Nome do Produto", "Descrição do Produto", "Categoria", "Data de Entrada", "Quantidade de Entrada", "Preço por unidade", "Valor total", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEntrada.setRowHeight(24);
        jTableEntrada.setRowMargin(4);
        jScrollPane2.setViewportView(jTableEntrada);
        if (jTableEntrada.getColumnModel().getColumnCount() > 0) {
            jTableEntrada.getColumnModel().getColumn(0).setMinWidth(50);
            jTableEntrada.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableEntrada.getColumnModel().getColumn(1).setMinWidth(100);
            jTableEntrada.getColumnModel().getColumn(1).setMaxWidth(180);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1846, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setViewportView(jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        imprimirEntrada.setBackground(new java.awt.Color(255, 255, 255));
        imprimirEntrada.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        imprimirEntrada.setForeground(new java.awt.Color(0, 153, 255));
        imprimirEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer-4-24.png"))); // NOI18N
        imprimirEntrada.setText("Imprimir");
        imprimirEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimirEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEntradaPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(424, 424, 424)
                .addComponent(imprimirEntrada)
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntradaPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(imprimirEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Entradas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jTableSaida.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Produto", "Descrição do Produto", "Categoria", "Data de Saída", "Quantidade de Saída", "Preço por unidade", "Valor total de Saída", "Por"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSaida.setRowHeight(24);
        jTableSaida.setRowMargin(4);
        jScrollPane5.setViewportView(jTableSaida);
        if (jTableSaida.getColumnModel().getColumnCount() > 0) {
            jTableSaida.getColumnModel().getColumn(0).setMinWidth(100);
            jTableSaida.getColumnModel().getColumn(0).setMaxWidth(180);
        }

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1846, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane3.setViewportView(jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel13.setText("Saídas no Periodo:");

        lblSaidaPeriodo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblSaidaPeriodo.setText("0.0 MZN");

        imprimirSaida.setBackground(new java.awt.Color(255, 255, 255));
        imprimirSaida.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        imprimirSaida.setForeground(new java.awt.Color(0, 153, 255));
        imprimirSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer-4-24.png"))); // NOI18N
        imprimirSaida.setText("Imprimir");
        imprimirSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimirSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirSaidaActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(26, 118, 141));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Saídas no Mês de:");

        jComboBoxMesSaida.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jComboBoxMesSaida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBoxMesSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxMesSaida.setFocusable(false);
        jComboBoxMesSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMesSaidaMouseClicked(evt);
            }
        });
        jComboBoxMesSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesSaidaActionPerformed(evt);
            }
        });
        jComboBoxMesSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxMesSaidaKeyPressed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Data final:");

        jDateChooserSaidaFinal.setDateFormatString("dd - MM - yyyy");
        jDateChooserSaidaFinal.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Saídas entre datas:");

        jDateChooserSaidaInicial.setDateFormatString("dd - MM - yyyy");
        jDateChooserSaidaInicial.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("até");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-8-16.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Selecione o Outro mecanismo de Pesquisa:");

        jRadioButtonSaidaMesPassado.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupSaida.add(jRadioButtonSaidaMesPassado);
        jRadioButtonSaidaMesPassado.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonSaidaMesPassado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSaidaMesPassado.setText("Saídas do Mês Passado");
        jRadioButtonSaidaMesPassado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonSaidaMesPassado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaidaMesPassadoActionPerformed(evt);
            }
        });

        jRadioButtonSaidaMesActual.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupSaida.add(jRadioButtonSaidaMesActual);
        jRadioButtonSaidaMesActual.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonSaidaMesActual.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSaidaMesActual.setText("Saídas do Mês Actual");
        jRadioButtonSaidaMesActual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonSaidaMesActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaidaMesActualActionPerformed(evt);
            }
        });

        jRadioButtonSaidaMesOntem.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupSaida.add(jRadioButtonSaidaMesOntem);
        jRadioButtonSaidaMesOntem.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonSaidaMesOntem.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSaidaMesOntem.setText("Saídas do dia de Ontem");
        jRadioButtonSaidaMesOntem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonSaidaMesOntem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaidaMesOntemActionPerformed(evt);
            }
        });

        jRadioButtonSaidaHoje.setBackground(new java.awt.Color(26, 118, 141));
        buttonGroupSaida.add(jRadioButtonSaidaHoje);
        jRadioButtonSaidaHoje.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jRadioButtonSaidaHoje.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSaidaHoje.setText("Saídas do dia de Hoje");
        jRadioButtonSaidaHoje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButtonSaidaHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSaidaHojeActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Código do Produto:");

        txtIdProdutoSaida.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtIdProdutoSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNomeProdutoSaida.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Nome do Produto:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSaidaMesPassado)
                                    .addComponent(txtIdProdutoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSaidaMesActual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonSaidaMesOntem))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel37)
                                            .addComponent(txtNomeProdutoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMesSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSaidaHoje)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooserSaidaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooserSaidaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(29, 29, 29))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserSaidaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMesSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jDateChooserSaidaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSaidaMesPassado)
                    .addComponent(jRadioButtonSaidaMesActual)
                    .addComponent(jRadioButtonSaidaMesOntem)
                    .addComponent(jRadioButtonSaidaHoje))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProdutoSaida))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProdutoSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSaidaPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imprimirSaida)
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaidaPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(imprimirSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Saídas", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirSaidaActionPerformed
        JOptionPane.showMessageDialog(this,
                "Ops!.. O relatório estará disponivel assim que terminar a manutenção",
                SystemMessage.SYSTEM_NAME,
                JOptionPane.INFORMATION_MESSAGE);        }//GEN-LAST:event_imprimirSaidaActionPerformed

    private void imprimirEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirEntradaActionPerformed
        JOptionPane.showMessageDialog(this,
                "Ops!.. O relatório estará disponivel assim que terminar a manutenção",
                SystemMessage.SYSTEM_NAME,
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_imprimirEntradaActionPerformed

    private void jComboBoxMesEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMesEntradaMouseClicked

    }//GEN-LAST:event_jComboBoxMesEntradaMouseClicked

    private void jComboBoxMesEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesEntradaActionPerformed
        int mes = jComboBoxMesEntrada.getSelectedIndex() + 1;
        atualizarEntradaProduto(produtoController.retornarProdutoPeloMesEntrada(mes));

        if (jTableEntrada.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Nenhum produto foi cadastrado no mês de " + jComboBoxMesEntrada.getSelectedItem(),
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxMesEntradaActionPerformed

    private void jComboBoxMesEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxMesEntradaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesEntradaKeyPressed

    private void jRadioButtonEntradaMesPassadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaMesPassadoActionPerformed
        atualizarEntradaProduto(produtoController.retornarProdutoPeloMesEntrada(LocalDate.now().getMonthValue() - 1));

        if (jTableEntrada.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Nenhum produto foi cadastrado no mês de " + LocalDate.now().getMonth().minus(1),
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButtonEntradaMesPassadoActionPerformed

    private void jRadioButtonEntradaMesAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaMesAtualActionPerformed
        atualizarEntradaProduto(produtoController.retornarProdutoPeloMesEntrada(LocalDate.now().getMonthValue()));

        if (jTableEntrada.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Nenhum produto foi cadastrado no mês Actual " + LocalDate.now().getMonth(),
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButtonEntradaMesAtualActionPerformed

    private void jRadioButtonEntradaOntemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaOntemActionPerformed
        atualizarEntradaProduto(produtoController.retornarProdutoPelaDataEntrada(ConversorDateTime.localDateTimeToUtilDate(LocalDateTime.now().minusDays(1))));

        if (jTableEntrada.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Nenhum produto foi cadastrado no dia de hoje " + LocalDate.now().getDayOfWeek(),
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEntradaOntemActionPerformed

    private void jRadioButtonEntradaDiaHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEntradaDiaHojeActionPerformed
        atualizarEntradaProduto(produtoController.retornarProdutoPelaDataEntrada(ConversorDateTime.localDateTimeToUtilDate(LocalDateTime.now())));

        if (jTableEntrada.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Nenhum produto foi cadastrado no dia de Ontem",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButtonEntradaDiaHojeActionPerformed

    private void jComboBoxMesSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMesSaidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesSaidaMouseClicked

    private void jComboBoxMesSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesSaidaActionPerformed

    private void jComboBoxMesSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxMesSaidaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesSaidaKeyPressed

    private void jRadioButtonSaidaMesPassadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaidaMesPassadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaidaMesPassadoActionPerformed

    private void jRadioButtonSaidaMesActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaidaMesActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaidaMesActualActionPerformed

    private void jRadioButtonSaidaMesOntemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaidaMesOntemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaidaMesOntemActionPerformed

    private void jRadioButtonSaidaHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSaidaHojeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSaidaHojeActionPerformed

    private void txtNomeProdutoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeProdutoEntradaKeyReleased
        atualizarEntradaProduto(produtoController.retornarProdutoPeloNome(txtNomeProdutoEntrada.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoEntradaKeyReleased

    private void txtCodigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBarrasKeyReleased
        atualizarEntradaProduto(produtoController.retornarProdutosPeloCodigoBarras(txtCodigoBarras.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBarrasKeyReleased

    private void txtIdProdutoEntradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdProdutoEntradaKeyReleased
        int idProduto = txtIdProdutoEntrada.getText().isEmpty() ? 1 : Integer.parseInt(txtIdProdutoEntrada.getText());
        atualizarEntradaProduto(produtoController.retornarProdutosPeloId(idProduto));          // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdutoEntradaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arquivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Arquivo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarEntrada;
    private javax.swing.ButtonGroup buttonGroupEntrada;
    private javax.swing.ButtonGroup buttonGroupSaida;
    private javax.swing.JButton imprimirEntrada;
    private javax.swing.JButton imprimirSaida;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxMesEntrada;
    private javax.swing.JComboBox jComboBoxMesSaida;
    private com.toedter.calendar.JDateChooser jDateChooserEntradaFinal;
    private com.toedter.calendar.JDateChooser jDateChooserEntradaInicial;
    private com.toedter.calendar.JDateChooser jDateChooserSaidaFinal;
    private com.toedter.calendar.JDateChooser jDateChooserSaidaInicial;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonEntradaDiaHoje;
    private javax.swing.JRadioButton jRadioButtonEntradaMesAtual;
    private javax.swing.JRadioButton jRadioButtonEntradaMesPassado;
    private javax.swing.JRadioButton jRadioButtonEntradaOntem;
    private javax.swing.JRadioButton jRadioButtonSaidaHoje;
    private javax.swing.JRadioButton jRadioButtonSaidaMesActual;
    private javax.swing.JRadioButton jRadioButtonSaidaMesOntem;
    private javax.swing.JRadioButton jRadioButtonSaidaMesPassado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEntrada;
    private javax.swing.JTable jTableSaida;
    private javax.swing.JLabel lblEntradaPeriodo;
    private javax.swing.JLabel lblSaidaPeriodo;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtIdProdutoEntrada;
    private javax.swing.JTextField txtIdProdutoSaida;
    private javax.swing.JTextField txtNomeProdutoEntrada;
    private javax.swing.JTextField txtNomeProdutoSaida;
    // End of variables declaration//GEN-END:variables

    private void configuracoes() {
        setLocationRelativeTo(this);
        this.setIconImage(new ImageIcon(getClass().getResource(SystemMessage.IMAGE_URL)).getImage());
        this.setTitle(SystemMessage.SYSTEM_NAME + " - Arquivo de produtos da empresa");
        atualizarEntradaProduto(produtoController.retornarTodosProdutos());

        txtCodigoBarras.setDocument(new Expressoes.InternalClass());
        txtNomeProdutoEntrada.setDocument(new Expressoes.InternalClass());
        txtIdProdutoEntrada.setDocument(new Expressoes.InternalClassDigit());
    }

    /*
    =========================Entrada Produto ===========================
     */
    private void atualizarEntradaProduto(List<com.dmz.stock.model.Produto> produtos) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableEntrada.getModel();
        defaultTableModel.setNumRows(0);
        int size = produtos.size();

        for (int i = 0; i < size; i++) {
            com.dmz.stock.model.Fornecedor fornecedor = new FornecedorProdutoController().retornarFornecedorPorProduto(produtos.get(i).getId());

            defaultTableModel.addRow(new Object[]{
                (i + 1),
                produtos.get(i).getId(),
                produtos.get(i).getNome(),
                produtos.get(i).getDescricao(),
                produtos.get(i).getCategoria(),
                produtos.get(i).getDataEntrada(),
                produtos.get(i).getQuantidade(),
                produtos.get(i).getValorPorUnidade() + " MZN",
                produtos.get(i).getValorTotal() + " MZN",
                fornecedor.getNomeFornecedor()
            });
        }

        double valor = 0;
        for (int i = 0; i < jTableEntrada.getRowCount(); i++) {
            valor += Double.parseDouble(jTableEntrada.getValueAt(i, 8).toString().replaceAll(" MZN", "").trim());
        }
        lblEntradaPeriodo.setText(ConversorValores.currencyMozambique(valor).replaceAll("MZN", "").trim() + " MZN");

    }

    /*
    =========================Saída Produto ===========================
     */
}
