package com.dmz.stock.view;

import com.dmz.stock.auxiliar.AuxiliarClass;
import com.dmz.stock.auxiliar.Expressoes;
import com.dmz.stock.controller.ControllerContactoFornecedor;
import com.dmz.stock.model.ContactoEmail;
import configuracoes.SystemMessage;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kennedy Melvin Serafim
 *
 */
public class ContactoEmailFornecedor extends javax.swing.JDialog {

    private static List<ContactoEmail> emailGeneric = new ArrayList<>();

    /**
     *
     * @return
     */
    public static List<ContactoEmail> getEmailGeneric() {
        return emailGeneric;
    }

    /**
     *
     * @param phoneGeneric
     */
    public static void setEmailGeneric(List<ContactoEmail> phoneGeneric) {
        ContactoEmailFornecedor.emailGeneric = phoneGeneric;
    }

    /**
     *
     * @param parent
     * @param modal
     */
    public ContactoEmailFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atalhoTeclado();
        configuracoes();
    }
 
    /**
     * 
     * @param parent
     * @param modal
     * @param email 
     */
    public ContactoEmailFornecedor(java.awt.Frame parent, boolean modal, ContactoEmail email) {
        super(parent, modal);
        if (validateEmailExist(email)) {
            ContactoEmailFornecedor.emailGeneric.add(email);
        }
        initComponents();
        atalhoTeclado();
        configuracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnAddTable = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtEmailGeneric = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cli_Master 1.1 - Endereço Electrónico");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        tableEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tableEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Endereço Electrónico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEmail.setRowHeight(24);
        tableEmail.setRowMargin(4);
        jScrollPane1.setViewportView(tableEmail);
        if (tableEmail.getColumnModel().getColumnCount() > 0) {
            tableEmail.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Endereço Electrónico:");

        btnExcluir.setBackground(new java.awt.Color(255, 51, 0));
        btnExcluir.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash-9-24.png"))); // NOI18N
        btnExcluir.setText("Excluir (Del)");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAddTable.setBackground(new java.awt.Color(255, 255, 255));
        btnAddTable.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnAddTable.setForeground(new java.awt.Color(26, 118, 141));
        btnAddTable.setText("+");
        btnAddTable.setToolTipText("Adicionar na tabela");
        btnAddTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 51, 51));
        btnSair.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account-logout-16.png"))); // NOI18N
        btnSair.setText("Sair (Esc)");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        txtEmailGeneric.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtEmailGeneric.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailGenericKeyPressed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 153, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/available-updates-16.png"))); // NOI18N
        btnEditar.setText("Editar (F2)");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adicionando Endereços Electrónicos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEmailGeneric, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddTable, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnEditar)
                                .addGap(28, 28, 28)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailGeneric, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddTable))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
 
        AuxiliarClass.formatarTextFieldAoSalvar(rootPane);
        ContactoEmail contactoEmail = new ContactoEmail(txtEmailGeneric.getText());
        if (validateEmailExist(contactoEmail)) {
            ContactoEmailFornecedor.emailGeneric.add(contactoEmail);
            atualizarTabela();
        }
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (tableEmail.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Não existe Endereço Electrónico na tabela para ser excluido.",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                int linha = tableEmail.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) tableEmail.getModel();
                model.removeRow(linha);
                emailGeneric.remove(linha);
                atualizarTabela();

            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(this, "Selecione o Endereço Electrónico na tabela para ser excluido.",
                        SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtEmailGenericKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailGenericKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (validateEmailExist(new ContactoEmail(txtEmailGeneric.getText()))) {
                ContactoEmailFornecedor.emailGeneric.add(new ContactoEmail(txtEmailGeneric.getText()));
                atualizarTabela();
            }
        }
    }//GEN-LAST:event_txtEmailGenericKeyPressed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tableEmail.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Não existe número de telefone na tabela para ser editado.",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                int linha = tableEmail.getSelectedRow();
                String subString = String.valueOf(tableEmail.getValueAt(linha, 1));

                DefaultTableModel model = (DefaultTableModel) tableEmail.getModel();
                model.removeRow(linha);
                emailGeneric.remove(linha);
                atualizarTabela();
                txtEmailGeneric.setText(subString);

            } catch (ArrayIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(this,
                        "Selecione o número de telefone na tabela para ser excluido.",
                        SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println(ex.getMessage());
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ContactoEmailFornecedor dialog = new ContactoEmailFornecedor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableEmail;
    private javax.swing.JTextField txtEmailGeneric;
    // End of variables declaration//GEN-END:variables

    private void configuracoes() {
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().
                getResource(SystemMessage.IMAGE_URL)).getImage());
        this.setTitle(SystemMessage.SYSTEM_NAME + " - Adicionando Endereços Elentrónicos");
        txtEmailGeneric.setDocument(new Expressoes.InternalClassEmail());
        atualizarTabela();
    }

    /**
     *
     */
    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tableEmail.getModel();
        model.setNumRows(0);
        int index = 1;

        for (ContactoEmail email : emailGeneric) {
            model.addRow(new Object[]{
                index++,
                email.getEmail()
            });
        }

        txtEmailGeneric.setText(null);
    }

    /**
     * ====================E-mail validation exist=====================
     *
     * @param contactoModel
     * @return
     */
    private boolean validateEmailExist(ContactoEmail email) {
        if (!Expressoes.validarEmail(email.getEmail())) {
            JOptionPane.showMessageDialog(this,
                    "Endereço Electrónico inválido",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else {

            for (ContactoEmail emailGeneric1 : ContactoEmailFornecedor.emailGeneric) {
                if (emailGeneric1.getEmail().equalsIgnoreCase(email.getEmail())) {
                    JOptionPane.showMessageDialog(null,
                            "O Endereço electrónico " + email.getEmail() + ", já está na lista ",
                            SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            }

            if (ControllerContactoFornecedor.verificarExistenciaEmailFornecedorController(email.getEmail())) {
                JOptionPane.showMessageDialog(null,
                        "Endereço electrónico indisponivel, tente outro.",
                        SystemMessage.SYSTEM_NAME,
                        JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        return true;
    }

    /**
     *
     */
    private void atalhoTeclado() {
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        /*
         ============================Botão para sair da tela======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "closeSystem");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("closeSystem", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnSair.doClick();
            }
        });

        /*
         ============================Botão para editar======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "editar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("editar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnEditar.doClick();
            }
        });

        /*
         ============================Botão para excluir======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "excluir");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("excluir", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnExcluir.doClick();
            }
        });
    }
}
