package com.dmz.stock.view;

import com.dmz.stock.auxiliar.AuxiliarClass;
import com.dmz.stock.auxiliar.Expressoes;
import com.dmz.stock.controller.ControllerContactoFornecedor;
import com.dmz.stock.controller.FornecedorController;
import com.dmz.stock.model.ContactoEmail;
import com.dmz.stock.model.ContactoTelefone;
import configuracoes.SystemMessage;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Kennedy Melvin Serafim
 */
public class Fornecedor extends javax.swing.JDialog {

    private String NUIT = "";

    /**
     *
     * @param parent
     * @param modal
     */
    public Fornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atalhoTeclado();
        configuracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNuit = new javax.swing.JFormattedTextField();
        txtPhone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdFornecedor = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAddEmail = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboPais = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboCidade = new javax.swing.JComboBox();
        btnAddPhone = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTipoProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAvenida = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFornecedor = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(26, 118, 141));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome do Fornecedor:");

        txtNomeFornecedor.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFornecedorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NUIT:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contacto Telefónico:");

        try {
            txtNuit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNuit.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtNuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuitActionPerformed(evt);
            }
        });

        try {
            txtPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+ (258) ## ### # ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ID do Fornecedor:");

        txtIdFornecedor.setEditable(false);
        txtIdFornecedor.setBackground(new java.awt.Color(26, 118, 141));
        txtIdFornecedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtIdFornecedor.setForeground(new java.awt.Color(204, 204, 204));
        txtIdFornecedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdFornecedor.setText("0");
        txtIdFornecedor.setBorder(null);
        txtIdFornecedor.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Endereço Electrónico:");

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnAddEmail.setBackground(new java.awt.Color(255, 255, 255));
        btnAddEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAddEmail.setForeground(new java.awt.Color(26, 118, 141));
        btnAddEmail.setText("+");
        btnAddEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmailActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("País:");

        jComboPais.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jComboPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um país...", "Moçambique" }));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cidade:");

        jComboCidade.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jComboCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma cidade...", "Maputo", "Matola", "Beira", "Nampula", "Chimoio", "Nacala", "Quelimane", "Tete", "Lichinga", "Xai-Xai", "Maxixe", "Manica", "Inhambane" }));

        btnAddPhone.setBackground(new java.awt.Color(255, 255, 255));
        btnAddPhone.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAddPhone.setForeground(new java.awt.Color(26, 118, 141));
        btnAddPhone.setText("+");
        btnAddPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPhoneActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 153, 204));
        btnCadastrar.setText("Cadastrar (F12)");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(0, 153, 255));
        btnAtualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/available-updates-16.png"))); // NOI18N
        btnAtualizar.setText("Actualizar (F5)");
        btnAtualizar.setAutoscrolls(true);
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tipo de Produto:");

        txtTipoProduto.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoProdutoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Avenida");

        txtAvenida.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboPais, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboCidade, 0, 1, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAddPhone)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddEmail))
                                    .addComponent(jLabel6)
                                    .addComponent(txtNuit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTipoProduto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAvenida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNuit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAtualizar))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Dados do Fornecedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Fornecedores Cadastrados no Sistema");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setText("Pesquisar Fornecedor Pelo Nome:");

        txtPesquisar.setBackground(new java.awt.Color(0, 153, 204));
        txtPesquisar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisar.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jTableFornecedor.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTableFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Código do Fornecedor", "Nome do Fornecedor", "Tipo de Produto", "NUIT", "País", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedor.setRowHeight(20);
        jTableFornecedor.setRowMargin(4);
        jTableFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableFornecedorMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFornecedor);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1427, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 51, 51));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account-logout-16.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/trash-9-24.png"))); // NOI18N
        btnEliminar.setText("Eliminar (Del)");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimparCampos.setBackground(new java.awt.Color(255, 102, 51));
        btnLimparCampos.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimparCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCampos.setText("Limpar Campos (F10)");
        btnLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 182, Short.MAX_VALUE)
                                .addComponent(btnEliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparCampos))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jSeparator2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Pretende fechar a tela de Fornecedor?",
                SystemMessage.SYSTEM_NAME, JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (validarCampos() && verificandoExistencia()) {
            com.dmz.stock.model.Fornecedor fornecedor = new com.dmz.stock.model.Fornecedor();
            fornecedor.setNomeFornecedor(txtNomeFornecedor.getText().trim());
            fornecedor.setNUIT(txtNuit.getText());
            fornecedor.setCidadeFornecedor(jComboCidade.getSelectedItem().toString());
            fornecedor.setPais(jComboPais.getSelectedItem().toString());
            fornecedor.setTipoProduto(txtTipoProduto.getText());
            long idFornecedor = new FornecedorController().criarFornecedorController(fornecedor);

            if (idFornecedor > 0) {
                JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com Sucesso.",
                        SystemMessage.SYSTEM_NAME, JOptionPane.INFORMATION_MESSAGE);

                new ControllerContactoFornecedor().criarFornecedorListaElectronicaController(
                        contactosElectronicosFornecedor(idFornecedor));

                new ControllerContactoFornecedor().criarFornecedorListaTelefonicaController(
                        contactosTelefonicoFornecedor(idFornecedor));
                limparCampos();
                atualizarTabela(FornecedorController.retornarTodosFornecedoresController());
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastar o Fornecedor.",
                        SystemMessage.SYSTEM_NAME, JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, SystemMessage.SUPPORT_TECH,
                        SystemMessage.SYSTEM_NAME, JOptionPane.ERROR_MESSAGE);
            }
        }
        Produto.atualizarComboBox();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        atualizarTabela(FornecedorController.retornarTodosFornecedoresNomeController(txtPesquisar.getText()));
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnAddEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmailActionPerformed
    }//GEN-LAST:event_btnAddEmailActionPerformed

    private void btnAddPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPhoneActionPerformed
        if (txtPhone.getText().trim().equals("+ (258)")) {
        } else {
            txtPhone.setText(null);
        }
    }//GEN-LAST:event_btnAddPhoneActionPerformed

    private void jTableFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseClicked
        int linha = jTableFornecedor.getSelectedRow();
        try {

            txtIdFornecedor.setText(jTableFornecedor.getValueAt(linha, 1).toString());
            txtNomeFornecedor.setText(jTableFornecedor.getValueAt(linha, 2).toString());
            txtTipoProduto.setText(jTableFornecedor.getValueAt(linha, 3).toString());
            txtNuit.setText(jTableFornecedor.getValueAt(linha, 4).toString());
            NUIT = jTableFornecedor.getValueAt(linha, 4).toString();
            jComboPais.setSelectedItem(jTableFornecedor.getValueAt(linha, 5).toString());
            jComboCidade.setSelectedItem(jTableFornecedor.getValueAt(linha, 6).toString());

            List<ContactoTelefone> contactoPhones = ControllerContactoFornecedor.
                    retornarTodosContactosTelefonicosFornecedorController(
                            Long.parseLong(jTableFornecedor.getValueAt(linha, 1).toString()));
            List<ContactoEmail> contactoEmails = ControllerContactoFornecedor.
                    retornarTodosContactosElectronicosFornecedorController(
                            Long.parseLong(jTableFornecedor.getValueAt(linha, 1).toString()));
            ContactoEmailFornecedor.setEmailGeneric(contactoEmails);
            ContactoTelefoneFornecedor.setPhoneGeneric(contactoPhones);

        } catch (ArrayIndexOutOfBoundsException e) {
        }

    }//GEN-LAST:event_jTableFornecedorMouseClicked

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (txtIdFornecedor.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this,
                    "Selecione o Fornecedor na tabela para actualizar os dados",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        } else if (validarCampos() && verificandoExistencia()) {
            com.dmz.stock.model.Fornecedor fornecedor = new com.dmz.stock.model.Fornecedor();
            fornecedor.setIdFornecedor(Long.parseLong(txtIdFornecedor.getText()));
            fornecedor.setNomeFornecedor(txtNomeFornecedor.getText().trim());
            fornecedor.setNUIT(txtNuit.getText());
            fornecedor.setCidadeFornecedor(jComboCidade.getSelectedItem().toString());
            fornecedor.setPais(jComboPais.getSelectedItem().toString());
            fornecedor.setTipoProduto(txtTipoProduto.getText());

            int confirmacao = JOptionPane.showConfirmDialog(this,
                    "Pretende actualizar os dados do Fornecedor",
                    SystemMessage.SYSTEM_NAME, JOptionPane.YES_NO_OPTION);

            if (confirmacao == JOptionPane.YES_OPTION) {

                if (new FornecedorController().atualizarDadosFornecedorController(fornecedor) > 0) {
                    JOptionPane.showMessageDialog(this, "Dados do Fornecedor actualizado com Sucesso.",
                            SystemMessage.SYSTEM_NAME, JOptionPane.INFORMATION_MESSAGE);

                    new ControllerContactoFornecedor().
                            atualizarFornecedorListaElectronicaController(fornecedor.getIdFornecedor());

                    new ControllerContactoFornecedor().
                            atualizarFornecedorListaTelefonicaController(fornecedor.getIdFornecedor());

                    new ControllerContactoFornecedor().criarFornecedorListaElectronicaController(
                            contactosElectronicosFornecedor(fornecedor.getIdFornecedor()));

                    new ControllerContactoFornecedor().criarFornecedorListaTelefonicaController(
                            contactosTelefonicoFornecedor(fornecedor.getIdFornecedor()));

                    limparCampos();
                    atualizarTabela(FornecedorController.retornarTodosFornecedoresController());
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao actualizar os dados do Fornecedor.",
                            SystemMessage.SYSTEM_NAME, JOptionPane.ERROR_MESSAGE);
                    JOptionPane.showMessageDialog(this, SystemMessage.SUPPORT_TECH,
                            SystemMessage.SYSTEM_NAME, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            if (jTableFornecedor.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Não existe Fornecedor registado no sistema para eliminar.",
                        SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            } else {
                int linha = jTableFornecedor.getSelectedRow();
                int confirmacao = JOptionPane.showConfirmDialog(this,
                        "Pretende apagar o registo do Fornecedor " + jTableFornecedor.getValueAt(linha, 2) + " ?",
                        SystemMessage.SYSTEM_NAME, JOptionPane.YES_NO_OPTION);

                if (confirmacao == JOptionPane.YES_OPTION) {
                    if (new FornecedorController().apagarRegisto(
                            Integer.valueOf(jTableFornecedor.getValueAt(linha, 1).toString())) > 0) {
                        JOptionPane.showMessageDialog(this, "Dados do Fornecedor apagado com Sucesso.",
                                SystemMessage.SYSTEM_NAME, JOptionPane.INFORMATION_MESSAGE);
                        atualizarTabela(FornecedorController.retornarTodosFornecedoresController());
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao apagar os dados do Fornecedor.",
                                SystemMessage.SYSTEM_NAME, JOptionPane.ERROR_MESSAGE);
                        JOptionPane.showMessageDialog(this,
                                SystemMessage.SUPPORT_TECH,
                                SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
            limparCampos();
        } catch (HeadlessException | NumberFormatException e) {

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this,
                    "Selecione na tabela o Enfermeiro que pretende apagar o seu registo.",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFornecedorActionPerformed
        txtNuit.requestFocus();
    }//GEN-LAST:event_txtNomeFornecedorActionPerformed

    private void txtNuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuitActionPerformed
        txtEmail.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuitActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtPhone.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProdutoActionPerformed
        txtAvenida.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProdutoActionPerformed

    private void jTableFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableFornecedorMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Fornecedor dialog = new Fornecedor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmail;
    private javax.swing.JButton btnAddPhone;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox jComboCidade;
    private javax.swing.JComboBox jComboPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableFornecedor;
    private javax.swing.JTextField txtAvenida;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdFornecedor;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JFormattedTextField txtNuit;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JFormattedTextField txtPhone;
    private javax.swing.JTextField txtTipoProduto;
    // End of variables declaration//GEN-END:variables

    private void configuracoes() {
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().
                getResource(SystemMessage.IMAGE_URL)).getImage());
        this.setTitle(SystemMessage.SYSTEM_NAME + " - Fornecedores dos Produtos em Estoque");

        btnSair.setVisible(false);
        txtEmail.setDocument(new Expressoes.InternalClassEmail());
        txtNomeFornecedor.setDocument(new Expressoes());
        txtPesquisar.setDocument(new Expressoes());
        txtTipoProduto.setDocument(new Expressoes());
        atualizarTabela(FornecedorController.retornarTodosFornecedoresController());
    }

    /**
     *
     * @return
     */
    private boolean validarCampos() {
        if (txtNomeFornecedor.getText().isEmpty() || txtNuit.getText().isEmpty()
                || txtTipoProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha todos os Campos do Formulário para continuar",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (ContactoTelefoneFornecedor.getPhoneGeneric().isEmpty()
                && txtPhone.getText().trim().equals("+ (258)")) {
            JOptionPane.showMessageDialog(this,
                    "Digite pelo menos um número de telefone.",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (ContactoEmailFornecedor.getEmailGeneric().isEmpty() && txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Digite pelo menos um Endereço Electrónico.",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (jComboPais.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecione o País do Fornecedor",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;

        } else if (jComboCidade.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Selecione  Cidade do Fornecedor",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     *
     * @return
     */
    private boolean verificandoExistencia() {

        /*
         ======================Verificando NUIT=================
         */
        if (!NUIT.equalsIgnoreCase(txtNuit.getText()) && FornecedorController.verificarNuitController(txtNuit.getText())) {
            JOptionPane.showMessageDialog(this, "O NUIT digitado já existe.",
                    SystemMessage.SYSTEM_NAME,
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        /*
         ======================Verificando E-mail=================
         */
        if (ControllerContactoFornecedor.verificarExistenciaEmailFornecedorController(txtEmail.getText())) {
            JOptionPane.showMessageDialog(null,
                    "Endereço electrónico indisponivel, tente outro.",
                    SystemMessage.SYSTEM_NAME,
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        for (ContactoEmail contactoEmail : ContactoEmailFornecedor.getEmailGeneric()) {
            if (ControllerContactoFornecedor.verificarExistenciaEmailFornecedorController(contactoEmail.getEmail())) {
                JOptionPane.showMessageDialog(null,
                        "Digite pelo menos um Endereço Electronico válido",
                        SystemMessage.SYSTEM_NAME,
                        JOptionPane.WARNING_MESSAGE);
                ContactoEmailFornecedor.setEmailGeneric(new ArrayList<>());
                return false;
            }
        }

        /*
         ======================Verificando número de telefone=================
         */
        if (ControllerContactoFornecedor.verificarExistenciaTelefoneFornecedorController(txtPhone.getText())) {
            JOptionPane.showMessageDialog(null,
                    "Número de telefone indisponivel, tente outro.",
                    SystemMessage.SYSTEM_NAME,
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        for (ContactoTelefone contactoPhone : ContactoTelefoneFornecedor.getPhoneGeneric()) {
            if (ControllerContactoFornecedor.verificarExistenciaTelefoneFornecedorController(contactoPhone.getTelefone())) {
                JOptionPane.showMessageDialog(null,
                        "Digite pelo menos um número de telefone válido.",
                        SystemMessage.SYSTEM_NAME,
                        JOptionPane.WARNING_MESSAGE);
                ContactoTelefoneFornecedor.setPhoneGeneric(new ArrayList<>());
                return false;
            }
        }

        return true;
    }

    /**
     *
     * @param idEnfermeiro
     * @return
     */
    private List<ContactoEmail> contactosElectronicosFornecedor(long idFornecedor) {
        List<ContactoEmail> contactoEmails = new ArrayList<>();
        ContactoEmail email;

        if (ContactoEmailFornecedor.getEmailGeneric().isEmpty()) {
            ContactoEmailFornecedor.getEmailGeneric().add(new ContactoEmail(txtEmail.getText()));
        }

        for (ContactoEmail emailGeneric : ContactoEmailFornecedor.getEmailGeneric()) {
            email = new ContactoEmail(emailGeneric.getEmail());
            email.setId(idFornecedor);

            contactoEmails.add(email);
        }

        return contactoEmails;
    }

    /**
     *
     * @param idFornecedor
     * @return
     */
    private List<ContactoTelefone> contactosTelefonicoFornecedor(long idFornecedor) {
        List<ContactoTelefone> contactoPhones = new ArrayList<>();
        ContactoTelefone phone;

        if (ContactoTelefoneFornecedor.getPhoneGeneric().isEmpty()) {
            ContactoTelefoneFornecedor.getPhoneGeneric().add(new ContactoTelefone(txtPhone.getText()));
        }

        for (ContactoTelefone phoneGeneric : ContactoTelefoneFornecedor.getPhoneGeneric()) {
            phone = new ContactoTelefone(phoneGeneric.getTelefone());
            phone.setId(idFornecedor);

            contactoPhones.add(phone);
        }

        return contactoPhones;
    }

    /**
     *
     * @param fornecedors
     */
    private void atualizarTabela(List<com.dmz.stock.model.Fornecedor> fornecedors) {
        DefaultTableModel tableModel = (DefaultTableModel) jTableFornecedor.getModel();
        tableModel.setNumRows(0);

        for (int i = 0; i < fornecedors.size(); i++) {
            tableModel.addRow(new Object[]{
                (i + 1),
                fornecedors.get(i).getIdFornecedor(),
                fornecedors.get(i).getNomeFornecedor(),
                fornecedors.get(i).getTipoProduto(),
                fornecedors.get(i).getNUIT(),
                fornecedors.get(i).getPais(),
                fornecedors.get(i).getCidadeFornecedor(),
                "Activo",});
        }
    }

    /**
     *
     */
    private void limparCampos() {
        AuxiliarClass.limparCampos(rootPane);
        txtIdFornecedor.setText("0");
        ContactoTelefoneFornecedor.setPhoneGeneric(new ArrayList<>());
        ContactoEmailFornecedor.setEmailGeneric(new ArrayList<>());
    }

    /**
     * =========================================
     */
    private void atalhoTeclado() {
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        /*
         ============================Botão para sair da tela======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "closeSystem");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("closeSystem", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnSair.doClick();
            }
        });

        /*
         ============================Botão para gravar======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0), "gravar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("gravar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnCadastrar.doClick();
            }
        });

        /*
         ============================Botão para gravar======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "actualizar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("actualizar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnAtualizar.doClick();
            }
        });

        /*
         ============================Botão para gravar======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), "limpar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("limpar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnLimparCampos.doClick();
            }
        });

        /*
         ============================Botão para gravar======================
         */
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "apagar");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("apagar", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                btnEliminar.doClick();
            }
        });

    }
}
