package com.dmz.stock.view;

import com.dmz.stock.auxiliar.AuxiliarClass;
import com.dmz.stock.auxiliar.ConversorDateTime;
import com.dmz.stock.auxiliar.ConversorValores;
import com.dmz.stock.auxiliar.Expressoes;
import com.dmz.stock.controller.FornecedorController;
import com.dmz.stock.controller.FornecedorProdutoController;
import com.dmz.stock.controller.ProdutoController;
import com.dmz.stock.model.Categorias;
import configuracoes.SystemMessage;
import java.awt.Cursor;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author seraf
 */
public class Produto extends javax.swing.JFrame {

    private static final Produto INSTANCE = new Produto();
    ProdutoController produtoController = new ProdutoController();

    public static Produto getInstance() {
        Produto.atualizarComboBox();

        return INSTANCE;
    }

    /**
     * Creates new form Produto
     */
    private Produto() {
        initComponents();
        formatarData();
        configuracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricacao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooserCompraProduto = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtDataEntrada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uJComboBoxFornecedor = new componentes.UJComboBox();
        lblAddFornecedor = new javax.swing.JLabel();
        uJComboBoxFornecedorTipoProduto = new componentes.UJComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtQuantidadeMinima = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPrecoCaixa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtValorEstoque = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtUnidadeCaixa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        uJComboBoxIdFornecedor = new componentes.UJComboBox();
        jLabel21 = new javax.swing.JLabel();
        txtValorCompra = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooserValidade = new com.toedter.calendar.JDateChooser();
        uJComboBoxCategoria = new componentes.UJComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Produtos");

        jPanel2.setBackground(new java.awt.Color(26, 118, 141));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código de Barras:");

        txtCodigoBarras.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtCodigoBarras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBarrasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição do Produto:");

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDescricacao.setColumns(20);
        txtDescricacao.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtDescricacao.setRows(5);
        txtDescricacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(txtDescricacao);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Imagem do Produto:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblImagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome do Produto:");

        txtNomeProduto.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtNomeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de entrada:");

        jDateChooserCompraProduto.setDateFormatString("dd - MM - yyyy");
        jDateChooserCompraProduto.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data da Compra:");

        txtDataEntrada.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        txtDataEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataEntrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDataEntrada.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria do Produto:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fornecedor do Produto:");

        uJComboBoxFornecedor.setAutocompletar(true);
        uJComboBoxFornecedor.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        uJComboBoxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uJComboBoxFornecedorActionPerformed(evt);
            }
        });

        lblAddFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye-16.png"))); // NOI18N
        lblAddFornecedor.setToolTipText("Adicionar fornecedor");
        lblAddFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddFornecedorMouseClicked(evt);
            }
        });

        uJComboBoxFornecedorTipoProduto.setAutocompletar(true);
        uJComboBoxFornecedorTipoProduto.setEnabled(false);
        uJComboBoxFornecedorTipoProduto.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de Produto fornecido:");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantidade de produtos (CX):");

        txtQuantidade.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Quantidade mínima:");

        txtQuantidadeMinima.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtQuantidadeMinima.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidadeMinima.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQuantidadeMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeMinimaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Preço por caixa:");

        txtPrecoCaixa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPrecoCaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecoCaixa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPrecoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoCaixaActionPerformed(evt);
            }
        });
        txtPrecoCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecoCaixaKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Valor total em estoque:");

        txtValorEstoque.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtValorEstoque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorEstoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtValorEstoque.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MZN");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Carregar...");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtUnidadeCaixa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtUnidadeCaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnidadeCaixa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUnidadeCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadeCaixaActionPerformed(evt);
            }
        });
        txtUnidadeCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnidadeCaixaKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Unidade por caixa:");

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MZN");

        txtValorCompra.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtValorCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtValorCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorCompraFocusLost(evt);
            }
        });
        txtValorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCompraActionPerformed(evt);
            }
        });
        txtValorCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorCompraKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Valor total da compra:");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("MZN");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Data de válidade:");

        jDateChooserValidade.setDateFormatString("dd - MM - yyyy");
        jDateChooserValidade.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        uJComboBoxCategoria.setAutocompletar(true);
        uJComboBoxCategoria.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrecoCaixa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17))
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(uJComboBoxCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodigoBarras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uJComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAddFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtValorEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel21)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(347, 479, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23))
                            .addComponent(jLabel9))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtUnidadeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserCompraProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(uJComboBoxFornecedorTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(uJComboBoxIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooserValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addContainerGap())))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(11, 11, 11)
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(uJComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(uJComboBoxFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(lblAddFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(11, 11, 11)
                                .addComponent(jDateChooserCompraProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)
                                .addComponent(uJComboBoxFornecedorTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(11, 11, 11)
                                .addComponent(jDateChooserValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnidadeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uJComboBoxIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtValorEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account-logout-16.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-user-3-24.png"))); // NOI18N
        jButton2.setText("Gravar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(26, 118, 141));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/list-ingredients-24.png"))); // NOI18N
        jButton3.setText("Lista de Produtos");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("** CX = Caixa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (validarCampos() && verificarCodigoBarras()) {
            registarProduto(dadosProduto());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        jDateChooserCompraProduto.requestFocus();
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void lblAddFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddFornecedorMouseClicked
        new Fornecedor(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_lblAddFornecedorMouseClicked

    private void uJComboBoxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uJComboBoxFornecedorActionPerformed
        if (uJComboBoxFornecedor.isPopupVisible()) {
            uJComboBoxFornecedorTipoProduto.setSelectedIndex(uJComboBoxFornecedor.getSelectedIndex());
            uJComboBoxIdFornecedor.setSelectedIndex(uJComboBoxFornecedor.getSelectedIndex());
        }
    }//GEN-LAST:event_uJComboBoxFornecedorActionPerformed

    private void txtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyReleased
        calcularValorTotal();
        txtValorCompra.setText(txtValorEstoque.getText());
    }//GEN-LAST:event_txtQuantidadeKeyReleased

    private void txtUnidadeCaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadeCaixaKeyReleased
        calcularValorTotal();
    }//GEN-LAST:event_txtUnidadeCaixaKeyReleased

    private void txtPrecoCaixaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoCaixaKeyReleased
        calcularValorTotal();
        txtValorCompra.setText(txtValorEstoque.getText());
    }//GEN-LAST:event_txtPrecoCaixaKeyReleased

    private void txtCodigoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBarrasActionPerformed
        txtNomeProduto.requestFocus();
    }//GEN-LAST:event_txtCodigoBarrasActionPerformed

    private void txtValorCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCompraKeyReleased
        // TODO add your handling code here:
        String quantidadeProduto = txtQuantidade.getText().isEmpty() ? "0" : txtQuantidade.getText();
        String valorTotalCompra = txtValorCompra.getText().isEmpty() ? "0" : ConversorValores.removerVirgula(txtValorCompra.getText());

        BigDecimal valorPorCaixa = new BigDecimal("0");

        try {
            if (Integer.parseInt(quantidadeProduto) != 0) {
                valorPorCaixa = new BigDecimal(valorTotalCompra).divide(new BigDecimal(quantidadeProduto));
            }
        } catch (NumberFormatException e) {
        }

        txtPrecoCaixa.setText(ConversorValores.currencyMozambique(
                Double.parseDouble(valorPorCaixa.toString())).replaceAll("MZN", ""));
    }//GEN-LAST:event_txtValorCompraKeyReleased

    private void txtPrecoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoCaixaActionPerformed
        txtValorCompra.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoCaixaActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        txtQuantidadeMinima.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtQuantidadeMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeMinimaActionPerformed
        txtUnidadeCaixa.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeMinimaActionPerformed

    private void txtUnidadeCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeCaixaActionPerformed
        txtPrecoCaixa.requestFocus();
    }//GEN-LAST:event_txtUnidadeCaixaActionPerformed

    private void txtValorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompraActionPerformed
        txtDescricacao.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraActionPerformed

    private void txtValorCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorCompraFocusLost

        txtValorCompra.setText(ConversorValores.currencyMozambique(
                Double.parseDouble(txtValorCompra.getText())).replaceAll("MZN", ""));
    }//GEN-LAST:event_txtValorCompraFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Produto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooserCompraProduto;
    private com.toedter.calendar.JDateChooser jDateChooserValidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddFornecedor;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtDataEntrada;
    private javax.swing.JTextArea txtDescricacao;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPrecoCaixa;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidadeMinima;
    private javax.swing.JTextField txtUnidadeCaixa;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtValorEstoque;
    private componentes.UJComboBox uJComboBoxCategoria;
    private static componentes.UJComboBox uJComboBoxFornecedor;
    private static componentes.UJComboBox uJComboBoxFornecedorTipoProduto;
    private static componentes.UJComboBox uJComboBoxIdFornecedor;
    // End of variables declaration//GEN-END:variables

    private void configuracoes() {
        setLocationRelativeTo(this);
        this.setIconImage(new ImageIcon(getClass().getResource(SystemMessage.IMAGE_URL)).getImage());
        this.setTitle(SystemMessage.SYSTEM_NAME + " - Entrada de Produtos");

        uJComboBoxIdFornecedor.setVisible(false);
        txtDataEntrada.setText(ConversorDateTime.localDateToString(LocalDate.now()));
        txtQuantidade.setDocument(new Expressoes.InternalClassDigit());
        txtQuantidadeMinima.setDocument(new Expressoes.InternalClassDigit());
        txtUnidadeCaixa.setDocument(new Expressoes.InternalClassDigit());
        txtPrecoCaixa.setDocument(new Expressoes.InternalClassCurrency());
        txtValorEstoque.setDocument(new Expressoes.InternalClassCurrency());
        txtValorCompra.setDocument(new Expressoes.InternalClassCurrency());
        txtCodigoBarras.setDocument(new Expressoes.InternalClassEmail());
        txtNomeProduto.setDocument(new Expressoes());
        txtDescricacao.setDocument(new Expressoes.InternalClassToUpperCase());

        for (String categoria : new Categorias().getCategorias()) {
            uJComboBoxCategoria.addItem(categoria);
        }

    }

    private void formatarData() {
        //Pegando a data atual e convertendo
        jDateChooserCompraProduto.setDate(
                ConversorDateTime.localDateTimeToUtilDate(
                        LocalDateTime.now()));

        jDateChooserValidade.setDate(ConversorDateTime.localDateTimeToUtilDate(LocalDateTime.now()));

        //Colocando o limite minimo da data
        jDateChooserCompraProduto.setMinSelectableDate(
                ConversorDateTime.localDateTimeToUtilDate(
                        LocalDateTime.now().minusDays(365)));

        jDateChooserValidade.setMinSelectableDate(ConversorDateTime.localDateTimeToUtilDate(
                LocalDateTime.now().minusDays(0))
        );

        //Colocando o limite maximo da data
        jDateChooserCompraProduto.setMaxSelectableDate(
                ConversorDateTime.localDateTimeToUtilDate(
                        LocalDateTime.now().plusDays(0)));

    }

    /**
     *
     */
    public static void atualizarComboBox() {
        uJComboBoxFornecedor.clear();
        uJComboBoxFornecedorTipoProduto.clear();
        uJComboBoxIdFornecedor.clear();

        for (com.dmz.stock.model.Fornecedor fornecedor : FornecedorController.retornarTodosFornecedoresController()) {
            uJComboBoxFornecedor.addItem(fornecedor.getNomeFornecedor());
            uJComboBoxFornecedorTipoProduto.addItem(fornecedor.getTipoProduto());
            uJComboBoxIdFornecedor.addItem(fornecedor.getIdFornecedor());
        }
    }

    /**
     * Calculando o valor total de produtos em stock
     */
    private void calcularValorTotal() {
        String quantidadeProduto = txtQuantidade.getText().isEmpty() ? "0" : txtQuantidade.getText();
        String valorPorCaixa = txtPrecoCaixa.getText().isEmpty() ? "0" : ConversorValores.removerVirgula(txtPrecoCaixa.getText());

        BigDecimal valorTotalCaixa = new BigDecimal("0");

        try {
            valorTotalCaixa = new BigDecimal(valorPorCaixa)
                    .multiply(new BigDecimal(quantidadeProduto));
        } catch (NumberFormatException e) {
            System.err.println(e.getMessage());
        }

        txtValorEstoque.setText(ConversorValores.currencyMozambique(
                Double.parseDouble(valorTotalCaixa.toString())).replaceAll("MZN", ""));
    }

    /**
     *
     * @return
     */
    private com.dmz.stock.model.Produto dadosProduto() {
        com.dmz.stock.model.Produto produto = new com.dmz.stock.model.Produto();
        produto.setCategoria(uJComboBoxCategoria.getSelectedObject().toString());
        produto.setCodigoBarras(txtCodigoBarras.getText());
        produto.setDataCompra(jDateChooserCompraProduto.getDate());
        produto.setDataValidade(jDateChooserValidade.getDate());
        produto.setDescricao(txtDescricacao.getText());
        produto.setNome(txtNomeProduto.getText());
        produto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        produto.setQuantidadeMinima(Integer.parseInt(txtQuantidadeMinima.getText()));
        produto.setQuantidadePorCaixa(Integer.parseInt(txtUnidadeCaixa.getText()));
        produto.setValorPorUnidade(new BigDecimal(ConversorValores.removerVirgula(txtPrecoCaixa.getText())));
        produto.setValorTotal(new BigDecimal(ConversorValores.removerVirgula(txtValorCompra.getText())));

        return produto;
    }

    /**
     *
     * @param produto
     */
    private void registarProduto(com.dmz.stock.model.Produto produto) {
        int idProduto = produtoController.registarProduto(produto);
        int idFornecedor = Integer.parseInt(uJComboBoxIdFornecedor.getSelectedItem().toString());

        if (idProduto > 0) {
            JOptionPane.showMessageDialog(this,
                    "Produto registado com sucesso no sistema",
                    SystemMessage.SYSTEM_NAME, JOptionPane.INFORMATION_MESSAGE);

            new FornecedorProdutoController().criarFornecedorProduto(idFornecedor, idProduto);
            AuxiliarClass.limparCampos(rootPane);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Lamentamos, mas ocorreu algum erro ao registar o Produto",
                    SystemMessage.SYSTEM_NAME,
                    JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this,
                    SystemMessage.SUPPORT_TECH, SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     *
     * @return
     */
    private boolean validarCampos() {
        if (uJComboBoxFornecedor.getModel().getSize() == 0) {
            int confirmacao = JOptionPane.showConfirmDialog(this,
                    "Nenhum fornecedor está cadastrado no sistema.\n Pretende cadastrar um fornecedor?",
                    SystemMessage.SYSTEM_NAME,
                    JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                new Fornecedor(this, rootPaneCheckingEnabled).setVisible(rootPaneCheckingEnabled);
            }
            return false;
        } else if (txtCodigoBarras.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Digite o Código de Barras",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtNomeProduto.getText().isEmpty() || txtNomeProduto.getText().length() < 2) {
            JOptionPane.showMessageDialog(this,
                    "Digite o nome do produto",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (jDateChooserCompraProduto.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifique a Data da compra do Produto",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (jDateChooserValidade.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Verifique a Data de válidade do Produto",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtQuantidade.getText().isEmpty() || txtQuantidade.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this,
                    "A Quantidade de Produtos (CX) não pode ser negativa",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtPrecoCaixa.getText().isEmpty() ||  txtPrecoCaixa.getText().equalsIgnoreCase("0.0")) {
            JOptionPane.showMessageDialog(this,
                    "O preço por caixa do produto não pode ser negativo",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (txtValorCompra.getText().isEmpty() || txtValorCompra.getText().equalsIgnoreCase("0.0")) {
            JOptionPane.showMessageDialog(this,
                    "O valor total da compra do produto não pode ser negativo",
                    SystemMessage.SYSTEM_NAME, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     *
     * @return
     */
    private boolean verificarCodigoBarras() {
        com.dmz.stock.model.Produto produto = produtoController.retornarProdutoPeloCodigoBarras(txtCodigoBarras.getText());

        if (produto != null) {
            JOptionPane.showMessageDialog(this,
                    "O código de barras do produto já está registado no sistema para o produto "
                    + produto.getNome(),
                    SystemMessage.SYSTEM_NAME, WIDTH);
            return false;
        }
        return true;
    }
}
